import type { Vehicle } from "@/types/training";

export const vehicles = [
  {
    id: "training-car-01",
    kind: "car",
    name: "Ford Puma",
    manufacturer: "Ford",
    model: "Puma",
    transmission: "manual",
    offeringIds: ["b-manual"],
    image: {
      src: "/images/vehicles/ford-puma.png",
      alt: "Seçkin Sürücü Kursu logolu beyaz Ford Puma eğitim aracı",
      width: 371,
      height: 270,
    },
    active: true,
  },
  {
    id: "training-car-02",
    kind: "car",
    name: "Volkswagen Polo",
    manufacturer: "Volkswagen",
    model: "Polo",
    transmission: "manual",
    offeringIds: ["b-manual"],
    image: {
      src: "/images/vehicles/volkswagen-polo.png",
      alt: "Seçkin Sürücü Kursu logolu gümüş renkli Volkswagen Polo eğitim aracı",
      width: 356,
      height: 272,
    },
    active: true,
  },
  {
    id: "training-car-03",
    kind: "car",
    name: "Hyundai i10",
    manufacturer: "Hyundai",
    model: "i10",
    transmission: "automatic",
    offeringIds: ["b-automatic"],
    image: {
      src: "/images/vehicles/hyundai-i10.png",
      alt: "Seçkin Sürücü Kursu logolu beyaz Hyundai i10 eğitim aracı",
      width: 344,
      height: 278,
    },
    active: true,
  },
  {
    id: "training-motorcycle-01",
    kind: "motorcycle",
    name: "A1 eğitim motosikleti",
    manufacturer: null,
    model: null,
    transmission: null,
    offeringIds: ["a1"],
    image: null,
    active: true,
  },
  {
    id: "training-motorcycle-02",
    kind: "motorcycle",
    name: "A2 eğitim motosikleti",
    manufacturer: null,
    model: null,
    transmission: null,
    offeringIds: ["a2"],
    image: null,
    active: true,
  },
] as const satisfies readonly Vehicle[];
