import type { Vehicle } from "@/types/training";

export const vehicles = [
  {
    id: "training-car-01",
    kind: "car",
    name: "Ford Puma",
    manufacturer: "Ford",
    model: "Puma",
    transmission: "manual",
    offeringIds: ["b-manual"],
    image: {
      src: "/images/vehicles/ford-puma-manuel.png",
      alt: "Seçkin Sürücü Kursu logolu beyaz Ford Puma eğitim aracı",
      width: 1536,
      height: 1024,
    },
    active: true,
  },
  {
    id: "training-car-02",
    kind: "car",
    name: "Volkswagen Polo",
    manufacturer: "Volkswagen",
    model: "Polo",
    transmission: "manual",
    offeringIds: ["b-manual"],
    image: {
      src: "/images/vehicles/volkswagen-polo-manuel.png",
      alt: "Seçkin Sürücü Kursu logolu beyaz Volkswagen Polo eğitim aracı",
      width: 1122,
      height: 1402,
    },
    active: true,
  },
  {
    id: "training-car-03",
    kind: "car",
    name: "Hyundai i10",
    manufacturer: "Hyundai",
    model: "i10",
    transmission: "automatic",
    offeringIds: ["b-automatic"],
    image: {
      src: "/images/vehicles/hyundai-i10-otomatik.png",
      alt: "Seçkin Sürücü Kursu logolu beyaz Hyundai i10 eğitim aracı",
      width: 1536,
      height: 1024,
    },
    active: true,
  },
  {
    id: "training-motorcycle-01",
    kind: "motorcycle",
    name: "A1 Eğitim Motosikleti",
    manufacturer: null,
    model: null,
    transmission: null,
    offeringIds: ["a1"],
    image: {
      src: "/images/vehicles/a1-motosiklet.png",
      alt: "Kursumuzun beyaz A1 eğitim motosikleti",
      width: 1448,
      height: 1086,
    },
    active: true,
  },
  {
    id: "training-motorcycle-02",
    kind: "motorcycle",
    name: "A2 Eğitim Motosikleti",
    manufacturer: null,
    model: null,
    transmission: null,
    offeringIds: ["a2"],
    image: {
      src: "/images/vehicles/a2-motosiklet.png",
      alt: "Kursumuzun yeşil A2 eğitim motosikleti",
      width: 1448,
      height: 1086,
    },
    active: true,
  },
] as const satisfies readonly Vehicle[];
